update requirements
i was getting the following error when trying to run diii:

```
ModuleNotFoundError: No module named 'pkg_resources'
```

it seems like pkg_resources has been removed in newer versions of python (3.12+).